package com.stock.userproflie.dto; // Adjusted package name to 'dto' for structure

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Pattern;
import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class UserProfileDto {

    // Note: The 'id' is excluded as it's generated by the database/Entity

    @NotEmpty(message = "Name is required")
    private String name;

    @NotEmpty(message = "Email is required")
    @Pattern(
        regexp = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$",
        message = "Email should be valid (e.g. user@example.com)"
    )
    private String email;

    @NotEmpty(message = "Phone is required")
    @Pattern(
        regexp = "^\\+?[0-9\\s-]{7,15}$",
        message = "Phone should be valid (digits 7–15, optional +, spaces, or hyphens)"
    )
    private String phoneNumber;

    @NotEmpty(message = "Gender is required")
    private String gender;

    @NotEmpty(message = "Address is required")
    private String address;

    // profilePicture is handled via MultipartFile in the Controller/Service
    // and is not directly set by a form field in the DTO.
    // private String profilePicture; 
}